# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voice.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoice.proto\x12\nvoicescore\"5\n\x0b\x45valRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65xpected_phrase\x18\x02 \x01(\t\"?\n\x0c\x45valResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0c\n\x04pass\x18\x03 \x01(\x08\x32K\n\nVoiceScore\x12=\n\x08\x45valuate\x12\x17.voicescore.EvalRequest\x1a\x18.voicescore.EvalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALREQUEST']._serialized_start=27
  _globals['_EVALREQUEST']._serialized_end=80
  _globals['_EVALRESPONSE']._serialized_start=82
  _globals['_EVALRESPONSE']._serialized_end=145
  _globals['_VOICESCORE']._serialized_start=147
  _globals['_VOICESCORE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
